### ISSUE TITLE
Why this require NPM?

### ISSUE THREAD

**Issue by Pitometsu** [bryphe/merlin-language-server#18]
I want to use it with `emacs-lsp`.
JS and NPM looks unnecessary.
Can it be installed via `opam` only?

**Comment by bartekus** [comment]
You do not need either JS or NPM, per se, and the only reason why you see (the familiar to nodejs environment) package.json in this repo is due to [esy](https://github.com/esy/esy) (used here as a package manager / development workflow for native Reason /OCaml) using the same format as npm.

That being said, I think that it should be mostly possible to install it via opam, except for perhaps few packages, i.e: refmterr & rench to be specific.

**Comment by Pitometsu** [comment]
> npm install -g esy
Srly? Is `esy` written in js?
Or it's just a convenient (one of) way to install it?

**Comment by bartekus** [comment]
No, `esy` is not written in js, but rather `reason`, and then compiled down to js; and yes, it is for convenience, and to appeal to js developers working with `react`; who are looking to switch to `reason-react`.

**Comment by Pitometsu** [comment]
Thank you for support.
